jekyll/jekyll-import

lib/jekyll-import/importers/wordpressdotcom.rb
Prior to this PR, the XML importer for WordPress.com would ignore the `post_excerpt` field. This is useful for SEO purposes (for the meta description in templates) as well as for other potential uses when displaying the content in a list view.
=> Add post excerpt to WordPress.com importer

lib/jekyll-import/importers/tumblr.rb
Although this patch cannot improve this importer that does not parse markdown documents and highlited codes well, it avoids an undefined local variable or method error.
Closes #126
=> Pass a variable redirect_dir to avoid an undefined local variable.

lib/jekyll-import/importers/drupal7.rb
As shown in this Github Issue: [Problem extracting titles from Drupal 7 site](https://github.com/jekyll/jekyll-import/issues/90), `drupal7.rb` dumps a binary mess in each post instead of the Title string.
```yaml
title: !binary |-
SGVsbG8gV29ybGQ=
```
I have fixed this bug entirely by forcing the strings into Unicode format (and stripping any preceding and ending whitespace with `strip`):
```ruby
'title' => title.strip.force_encoding("UTF-8"),
```
That way, it works even for those  pesky titles with stray \xE2 junk that screws everything up.
Please merge this pull request to fix the Drupal 7 importer. Try it out.
=> Fix Title extraction in Drupal 7 import script

site/_importers/wordpress.md
These were the additional gems I had to install to run the WordPress importer. Might help to document them on the page.
=> Update wordpress.md with additional gems needed

lib/jekyll-import/importers/tumblr.rb
Fix for this error when importing a Tumblr blog with video posts with empty `video-player` field:
```
Fetching http://paramaggarwal.com/api/read/json/?num=50&start=0
Page: 1 - Posts: 50
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:136:in `post_to_hash': undefined method `<<' for false:FalseClass (NoMethodError)
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:47:in `block in process'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:47:in `map'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importers/tumblr.rb:47:in `process'
from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-import-0.5.3/lib/jekyll-import/importer. …
```
=> (Tumblr) Add nil check to prevent undefined method error (fixes #29)

lib/jekyll-import/importers/rss.rb
Otherwise it won't parse an Atom field.
Fixes #194.
=> Require all of rss when importing RSS feed.

lib/jekyll-import/importers/wordpress.rb, site/_importers/wordpress.md
I came across https://github.com/jekyll/jekyll-import/issues/185 when trying to import a multi site installation.
To give some background, the way that this installation has it configured, the sites are each stored as wp_x_ prefixes.
In order to support this I have added the `site-prefix` option which is prepended before all calls to these specific tables.
Import site `wp_2_`
```
ruby -rubygems -e 'require "jekyll-import";
JekyllImport::Importers::WordPress.run({
"dbname"      => "blogname",
"user"        => "username",
"password"    => "password",
"host"        => "blog.com",
"site_prefix" => "2_"
})'
```
=> Wordpress - Add Site Prefix 

lib/jekyll-import/importers/wordpress.rb, site/_importers/wordpress.md
Adds support for changing the extension for Wordpress posts.
Use case being I want my files as html.
```
JekyllImport::Importers::WordPress.run({
"extension" => "html"
})'
```
=> Wordpress File Extension

lib/jekyll-import/importers/wordpressdotcom.rb
Currently URLs created for downloaded images in `assets_folder` are not prepended with slash therefore images are being linked as relative URLs i.e `/2012/03/16/assets/myimage.jpg` instead of the correct absolute ones `/assets/myimage.jpg`.
The fix also adds support for `site.baseurl` which means the images will also be linked correctly when serving site from custom base URL.
More info in [forums](https://talk.jekyllrb.com/t/importing-wordpress-xml-downloads-images-to-assets-but-urls-to-this-dont-work/986).
=> Fix #211, wordpressdotcom import assets URLs

lib/jekyll-import/importers/wordpressdotcom.rb, test/test_wordpressdotcom_importer.rb
When importing an unpublished draft from wordpress.com, jekyll-import was raising an exception trying to parse its published date, which is set to `0000-00-00 00:00:00`. It was using this to prepend the publish-date to the filename in `./_posts`.
This pull request changes the WordpressDotCom import so that:
* it doesn't try to parse the zero dates
* it doesn't prepend the date to the filenames
* it stores drafts in `./_drafts` instead of `./_posts`
I also added a bunch of test coverage for the WordpressDotCom importer, mostly by pulling lots of logic into a separate class, `JekyllImport::Importers::WordpressDotCom::Item`, and constructing those with specific XML. The actual writing of files is still untested, but there's less going on there now.
=> Correctly handle wordpressdotcom drafts

lib/jekyll-import/importers/wordpressdotcom.rb, test/test_wordpressdotcom_importer.rb
It looks like there were some hiccups with the cleanup after merging #213:
* Some local variables were removed. This replaces their reference sites with calls to the appropriate Item methods.
* It was trying to call `.empty?` on an Hpricot::Doc, which doesn't support that method.
* This also stops including empty excerpts in a Post's metadata.
=> Fix post-merge hiccups after #213

lib/jekyll-import/importers/joomla3.rb, lib/jekyll/commands/import.rb, site/_importers/joomla.md, site/_importers/joomla3.md, site/_importers/jrnl.md
Hi,
Currently I am in the process of migrating a Joomla 3 blog to Jekyll. The existing Joomla importer supports 1.5 and possible 2.5 (need to double check). As of version 3, the table structure was changed though. Although I have never programmed in Ruby before, the Joomla import script looked easy enough for me to adapt. 
I am not a ruby programmer. I merely adapted an existing script. I did some testing, but not very formally. Also, I am not sure on best practices regarding branching and code style. 
In Joomla 1.5, the default table prefix was `jos_`.  This proved to be quite insecure, so in later versions, random table prefixes are used. Therefore, I made the prefix option mandatory. Failing to enter one will result in an error message. 
The main difference is that the sections and …
=> Joomla3 import

lib/jekyll-import/importers/joomla.rb
1. The importer was generating pages for articles outside the selected category.  Added parentheses so the proper precedence is enforced.
2. Joomla! article aliases are used to construct the filename as YYYY-MM-DD-alias.markdown.  Some aliases in the database I was importing were blank resulting in YYYY-MM-DD-.markdown filenames.  If more than one article was missing the alias and happened to be authored on the same day, each would overwrite the previous only leaving the last imported.  Using the title, when the alias was empty, resolved these conflicts.
3. Some aliases / titles contained characters that were illegal for filenames and the importer would terminate with an error when attempting to write the file.  Borrowed the sluggify method from the Wordpress importer to strip all illegal …
=> Joomla importer

lib/jekyll-import/importers/tumblr.rb
Post' slug was not added or was added malformed when containing non-url-friendly characters only. For example, having cyrillic title made post to have either empty (`no title`) or dashed (`----`, depending on spaces amount)  slug. This commit replaces all such slugs with post' id.
=> Fixed Tumblr importer malformed slugs

lib/jekyll-import/importers/tumblr.rb
They may contain umlauts and that breaks parsing, see #216.
=> Encode tumblr URIs before parsing

lib/jekyll-import/importers/blogger.rb
I came across error saying a URI encoded file name is too long for a converted file name.
```
ruby -rubygems -e 'require "jekyll-import";
quote>     JekyllImport::Importers::Blogger.run({
quote>       "source"                => "/Users/szkmp/Downloads/deletable/blog-10-10-2015.xml",
quote>       "no-blogger-info"       => false, # not to leave blogger-URL info (id and old URL) in the front matter
quote>       "replace-internal-link" => false, # replace internal links using the post_url liquid tag.
quote>     })'
/Users/szkmp/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-import-0.8.0/lib/jekyll-import/importers/blogger.rb:187:in `initialize': File name too long @ rb_sysopen - _drafts/2013-01-23-%E3%83%87%E3%83%99%E3%83%AD%E3%83%83%E3%83%91%E3%81%8C%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B …
```
=> Decode URI encoded multibyte file names

jekyll-import.gemspec, lib/jekyll-import/importers/wordpressdotcom.rb
The wordpress importer was failing to follow http->https redirections for my images (so it was failing to download them). This was due to open-uri not following these redirs.
Added the `open_uri_redirections` gem and changed the `open(uri)` call to:
``` ruby
open(uri, allow_redirections: :safe)
```
Also changed error logging method to say "Error" instead of "Errorr".
=> now follows 'safe' http->https redirs for images

lib/jekyll-import/importers/mt.rb, site/_importers/mt.md
Also, document the undocumented Movable Type importing options.
=> Add support for importing from PostgreSQL-backed Movable Type sites.

lib/jekyll-import/importers/drupal7.rb
This adds a `--types` command line option to allow the user to specify which node types to import from Drupal 7. This way the user can also import pages or any other content type.
It defaults to the ones the importer already did (blog posts, articles and stories), so that users are not forced to specify the node types and thus they won't see a difference if they don't need this ability.
=> Allow importing any Drupal 7 node type

lib/jekyll-import/importers/drupal7.rb
With the current Drupal 7 import script, there is no author data (very helpful when there are multi-author blogs, which is often the case with Drupal sites) nor nid attached to the imported posts. The nid can be extremely helpful in cases where you use a customized template to show Disqus comments or need to print other legacy-powered data on particular posts.
=> Add author and nid field to import from Drupal 7.

lib/jekyll-import/importers/drupal6.rb
When I try to import data from Drupal 6 I get the following error because the `mysql` gem is missing:
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': LoadError: cannot load such file -- mysql (Sequel::AdapterNotFound)
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/pieter/.gem/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/mysql.rb:6:in `rescue in <top (required)>'
from /home/pieter/.gem/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/mysql.rb:3:in `<top (required)>'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/pieter/.gem/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:98:in …
```
=> Drupal 6 importer depends on mysql.

lib/jekyll-import/importers/tumblr.rb
Tumblr might have changed the structure of its JSON recently. The jekyll Tumblr importer is currently stripping out the ending curly brace (results in an "unexpected token error" with JSON parser).
=> Tumblr: Update range of JSON readlines to extract JSON from JS (Tumblr may have changed structure of JSON)

lib/jekyll-import/importers/tumblr.rb
should not try to read all lines twice from same stream (`feed`).
looked up docs for ruby arrays and ranges.
=> Tumblr: fix stripping of JSONP characters from feed

jekyll-import.gemspec, lib/jekyll-import/importers/s9y_database.rb, lib/jekyll-import/importers/s9y_mysql.rb, site/_importers/s9y.md, site/_importers/s9ydatabase.md
Because I wanted to export my old blog and all I had was a MySQL dump, I created an `S9YDatabase` importer based on the [wordpress](http://import.jekyllrb.com/docs/wordpress/) importer.
Features:
- Export comments
- Export categories
- Export tags
- Export permalinks
- Reverse-markdown support
=> Add S9y database importer

lib/jekyll-import/importers/blogger.rb
Similar to the [WordPress importer](https://import.jekyllrb.com/docs/wordpress/), this PR adds support for importing comments from Blogger.
When `comments: true` is specified in `options` comments are written to a custom collection `_comments`. They are named according to the slug of the post, such as `2016-01-my-post-<number>.html` where `<number>` is a simple incrementing counter. To be able to connect comments with posts, there is a metadata field on the front matter `blogger_post_id` which refers to the post the comment is for (matches the `blogger_id` on posts).
Usage example can be seen on the blog I just imported, http://joscarsson.github.io/runtjordennu (warning, Swedish). The comments are added to the posts [through a generator](https://github.com/joscarsson/runtjordennu/blob/mast …
=> Add functionality for importing Blogger comments

lib/jekyll-import/importers/joomla.rb
joomla.rb was using Sequel.mysql, which appears to depend on the gem mysql.  This is depracated and replacing mysql with mysql2 works fine;  it is already in use for wordpress.rb.  I also added the requirement for the mysql2 gem, as this doesn't appear to work without that.
Details of my error message when running the vanilla joomla importer without mysql:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': LoadError: cannot load such file -- mysql (Sequel::AdapterNotFound)
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Library/Ruby/Gems/2.0.0/gems/sequel-4.34.0/lib/sequel/adapters/mysql.rb:6:in `rescue in <top …
```
=> joomla: use & require mysql2 instead of mysql

lib/jekyll-import/importers/tumblr.rb
Found these bugs after I ran into #252 
Fixing two bugs introduced recently:
- `feed` was getting read from twice, so the second time it was empty
- `ending` marks the index of the right-most `}`, but needed to be
bumped by 1 when referenced in the array
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
=> Tumblr: Fixing double-read and off-by-one error

lib/jekyll-import/importers/drupal6.rb, lib/jekyll-import/importers/drupal7.rb, lib/jekyll-import/importers/drupal_common.rb
Big refactoring of the Drupal importers.
All the code that was repeated on both Drupal6 and Drupal7 importers was pulled up into a generic `DrupalAbstract` class which implements the "core" logic of the Drupal importers and delegates the version-specific code to sub-classes.
I would appreciate it if someone could test importing non-Drupal content, though, because I don't have another blog to test the non-Drupal importers with.
=> Clean up the Drupal importers

lib/jekyll-import/importers/drupal_common.rb
@borfast, would you mind taking a 👀 at this? Addresses 2 of my comments. 😄 
/cc #235
=> DrupalCommon: centralize defaults & use config for layouts dir

site/_importers/joomla3.md
=> Fix for misnamed Joomla3 module in docs

lib/jekyll-import/importers/drupal7.rb
Using EOS around the query means we dont need the trailing quote.
=> Drupal 7: Remove uneeded double quote in SQL query

lib/jekyll-import/importers/drupal7.rb
See issue #288...
```
Sequel::DatabaseError: Mysql::Error: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'drupal7.fdb.body_value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```
=> Fixes SQL grouping error in #288

.travis.yml
Nokogiri no longer supports Ruby 1.9.3 it seems, causing tests to fail.
Given [1.9.3 is EOL](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/), IMHO it should not longer be supported by this Gem.
Also, [2.0 is EOL](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/) so there is no point adding that. And it seems [2.3 and 2.4](https://docs.travis-ci.com/user/languages/ruby/#Supported-Ruby-Versions-and-RVM) are not available yet either.
=> Updating Ruby and Jekyll versions for testing

_importers/joomla3.md
The current documentation implies that the "category" field requires a string when it actually needs the id of the category to be selected.
=> Corrected Joomla3 importer name and clarified "category" field

lib/jekyll-import/importers/wordpress.rb
The substitution was not being made because the arguments were reversed. This resulted in breaking HTML end tags imported from WordPress. The issue reporting this was closed due to inactivity, I've just now had some time to try to use Jekyll again.
=> WordPress: replace was backwards, broke end tags

lib/jekyll-import/importers/ghost.rb
This PR adds a few improvements to the Ghost importer.
- The note about weird Ghost date formats seems to no longer apply. When run against a current Ghost installation (tested with 0.11), all dates end up as 1970-01-01 because of the special trimming. This has been removed.
- If a post has been published, the importer now uses its publish date instead of its creation date.
- The importer now imports pages using slug-only filenames in the root directory with the 'page' layout.
=> Ghost: import drafts & pages, and fix issue with date extraction

jekyll-import.gemspec, lib/jekyll-import/importers/drupal_common.rb, lib/jekyll-import/importers/easyblog.rb, lib/jekyll-import/importers/ghost.rb, lib/jekyll-import/importers/joomla.rb, lib/jekyll-import/importers/joomla3.rb, lib/jekyll-import/importers/mephisto.rb, lib/jekyll-import/importers/mt.rb, lib/jekyll-import/importers/textpattern.rb, lib/jekyll-import/importers/typo.rb
Use and require mysql2 gem instead of mysql for the Joomla3 importer. Change similar to the one for the Joomla importer - #255.
=> Use mysql2 instead of mysql in Joomla3 importer

docs/_importers/joomla.md, docs/_importers/joomla3.md, lib/jekyll-import/importers/joomla.rb, lib/jekyll-import/importers/joomla3.rb
* Add option to specify the MySQL port for the Joomla importers
* Use Ruby 1.9 hash syntax
* Update the Joomla importers documentation
=> Add option to specify the MySQL port for the Joomla importers

lib/jekyll-import/importers/wordpressdotcom.rb
Imports passwords of password protected posts.
Again, I found this super useful, but feel free to decline if you don't want it 😄
=> WordPressDotCom: import post passwords

lib/jekyll-import/importers/wordpress.rb
In the WordPress importer, the `more_link` variable was never used so this option wasn't really doing anything (always passing `nil`).
=> WordPress: fix variable name for `more_anchor`

lib/jekyll-import/importers/wordpress.rb
Fixes missing site prefix in user table in the WordPress Importer. Tested on 4.9.4 WP DB.
=> Fixes missing site prefix in user table

lib/jekyll-import/importers/drupal_common.rb
#331 added support for PostgreSQL in the Drupal importers. According to the documentation, MySQL is supposed to be the default engine, but the `engine` parameter is now mandatory because the default value is not used. This PR fixes that by using the value that was added to the `DEFAULTS` hash.
/cc @kesara
=> Use mysql by default in Drupal importers.

lib/jekyll-import/importers/mt.rb
Fixing the error :
/Library/Ruby/Gems/2.3.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query': Mysql2::Error: Unknown column 'mt_placement__placement_entry_id' in 'where clause' (Sequel::DatabaseError)
=> Column name typo

.rubocop.yml, jekyll-import.gemspec
`$INPUT_RECORD_SEPARATOR` requires loading `"english"` from Ruby stdlib to initialize it.
So, its better remove the warning from Ruby by using the pre-initialized alternative `$/` especially since Rubocop does not complain about it now..
=> Replace uninitialized constant with alternative

.rubocop.yml, lib/jekyll-import/importers/tumblr.rb
Last Rubocop batch broke tumblr importer, this reverts the change and ignore `Lint/Loop` cop for now.
=> fix: Ignore Lint/Loop for tumblr

lib/jekyll/commands/import.rb
```
require "jekyll-import" > require "jekyll/commands/import" > require "jekyll-import" ...
```
=> Remove cyclic require of import command

.rubocop.yml, lib/jekyll-import/importers/blogger.rb, lib/jekyll-import/importers/joomla3.rb, lib/jekyll-import/importers/s9y_database.rb, lib/jekyll-import/importers/tumblr.rb, lib/jekyll-import/importers/typo.rb, lib/jekyll-import/importers/wordpress.rb
These importers modify string literals in various places.
It is easier and cleaner to simply disable `frozen_string_literal` pragma for these importers
Resolves #380
=> Unfreeze strings in importers that modify literals

lib/jekyll-import/importers/tumblr.rb, test/test_tumblr_importer.rb
Resolves #297 
When a `--format=md` is passed to `Importers::Tumblr` parse HTML input with Kramdown and render into Markdown fixed at line-length of 90 characters
=> Convert Tumblr content to Markdown when opted for

lib/jekyll-import/importers/wordpressdotcom.rb
`URI.parse` takes only one argument unlike `Kernel#open` as evident from the original `:open` replaced in https://github.com/jekyll/jekyll-import/commit/a23329709018deec7d821c2b23daef68d970e090. The `:allow_redirections` option is made available by the `open_uri_redirections` gem.
Replacing `URI.parse.open` here with a heavy-duty `OpenURI.open_uri` to allow reading the given uri along with `:allow_redirections` option and avoid raising a security flag from RuboCop
Resolves #387
=> Replace URI.parse.open with OpenURI.open_uri

lib/jekyll-import/importers/ghost.rb
fixed it in the according importer by dividing the timestamp value by 1000
=> ghost.db stores timestamps in ms, not seconds. Fixed the ghost importer.

lib/jekyll-import/util.rb, test/test_util.rb
Fix Util#wpautop method to escape backslash.
`String#gsub!` requires escape backslash if second argument as String.
https://docs.ruby-lang.org/en/2.6.0/String.html#method-i-gsub
=> Fix WP pre tag util raise error when value includes regexp

.rubocop.yml, .travis.yml, Gemfile, jekyll-import.gemspec
This plugin doesn't use Ruby 2.4 specific syntax and therefore we can relax the Ruby version constraint to the minimum testable version across the ecosystem: Ruby 2.3
Other changes include testing the plugin against jekyll 4.0 pre-release.
=> Re-introduce Ruby 2.3 support and test Jekyll 3.7+

lib/jekyll-import/importers/rss.rb
- Set `output` as `item.content_encoded` when `output` is an empty string.
- Ensure only *strings* are passed to be concatenated into the `output` string.
Closes #391
=> Extract encoded_content from feed

lib/jekyll-import/importers/rss.rb
`option` is expected to be a Hash. Therefore `option.to_s` is never going to be empty since even `{}.to_s` equals `"{}"`. Tracing the git history of the line of code shows that this is probably an error during merge-resolution.
I'm opting to use the more verbose `options["tag"].nil? || options["tag"].empty?` instead of `options["tag"].to_s.empty?` since this conditional is inside an `#each` block. Using the latter format would result in unnecessary allocations of `""` when `options["tag"] == nil`
=> Check whether option["tag"] is null or empty value

lib/jekyll-import/importers/rss.rb
Delegate to utility function in Core (`Jekyll::Utils.slugify` understands `mode: 'latin'` from Jekyll 3.7.0)
=> Slugify post name with Jekyll::Utils.slugify

docs/_importers/posterous.md
Link was set to movabletype.org
=> Fix link for Posterous importer

lib/jekyll-import/importers/s9y_database.rb
The method self.process_tags in s9y_database.rb wrongly checked the option :categories, likely due to a copy and paste error.
The fix is a one-liner
=> Fix wrong option in self.process_tags

lib/jekyll-import/importer.rb
When I try to run:
```ruby
ruby -e 'require "jekyll-import";
JekyllImport::Importers::WordPress.run({
})'
```
Per the instructions found [here](https://import.jekyllrb.com/docs/wordpress/).
It throws this error:
```sh
Traceback (most recent call last):
4: from -e:2:in `<main>'
3: from /home/thestranjer/Code/jekyll-import/lib/jekyll-import/importer.rb:22:in `run'
2: from /home/thestranjer/Code/jekyll-import/lib/jekyll-import/importer.rb:15:in `stringify_keys'
1: from /home/thestranjer/Code/jekyll-import/lib/jekyll-import/importer.rb:15:in `each_key'
/home/thestranjer/Code/jekyll-import/lib/jekyll-import/importer.rb:16:in `block in stringify_keys': can't add a new key into hash during iteration (RuntimeError)
```
This is because in the `JekyllImport::Importer::stringify_keys` method, it is …
=> Fix 'can't add a new key into hash during iteration' error

lib/jekyll-import/importers/wordpressdotcom.rb
This PR resolves #435 
A small change to put downloaded assets into /year/month subfolder. This is done by using the date of the post as the subfolder in the assets folder. This keeps the assets chronologically with the post, and reduces clashes as this is the same as how Wordpress store their files.
**Before:**
When I ran the import tool on my blog, I had 350 clashes of images being overwritten.
**After:**
I successfully ran this on my blog https://DavidBurela.wordpress.com, which has 13 years, 230 posts. I only ended up with 5 clashes (which was due to me referencing images in other posts).
*Note:* I have never coded in Ruby before. I naively implemented it with the smallest number of changes that I could to reduce bugs.
=> WordpressDotCom: put downloaded assets into /year/month subfolders to reduce clashes

lib/jekyll-import/importers/blogger.rb
URI doesn't contain the method `decode` anymore, raising the error:
```
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-import-0.20.0/lib/jekyll-import/importers/blogger.rb:189:in `tag_end': undefined method `decode' for URI:Module (NoMethodError)
from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/gems/3.0.0/gems/rexml-3.2.4/lib/rexml/parsers/streamparser.rb:36:in `parse'
from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-import-0.20.0/lib/jekyll-import/importers/blogger.rb:51:in `block in process'
from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-import-0.20.0/lib/jekyll-import/importers/blogger.rb:49:in `open'
from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-import-0.20.0/lib/jekyll-import/importers/blogger.rb:49:in `process'
from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-import-0.20.0/lib/jekyll-import …
```
=> Replace decode with decode_www_form_component

lib/jekyll-import/importers/drupal6.rb, lib/jekyll-import/importers/rss.rb, lib/jekyll-import/importers/s9y_database.rb
```text
lib/jekyll-import/importers/drupal6.rb:52:9: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||. (https://rubystyle.guide#if-as-a-modifier)
if sql_post_data[:alias]
^^
lib/jekyll-import/importers/rss.rb:32:7: C: Metrics/CyclomaticComplexity: Cyclomatic complexity for process is too high. [7/6]
def self.process(options) ...
^^^^^^^^^^^^^^^^^^^^^^^^^
lib/jekyll-import/importers/rss.rb:44:9: C: Metrics/BlockLength: Block has too many lines. [32/25]
rss.items.each do |item| ...
^^^^^^^^^^^^^^^^^^^^^^^^
lib/jekyll-import/importers/s9y_database.rb:371:15: C: Style/StderrPuts: Use warn instead of STDERR.puts to allow such output to be disabled. (https://rubystyle.guide#warn)
STDERR.puts …
```
=> Clean up code to make Rubocop happy

lib/jekyll-import/importers/drupal_common.rb
Alias markdown files were being generated in the current directory instead of the directory defined by the "source" configuration option.
This is my first time using jekyll, still trying to figure it out. I'm sorry if I missed something in how this is supposed to work.
=> Drupal aliases now respect the 'source' config

jekyll-import.gemspec
RDoc v6.4 has Psych v4 as a runtime dependency. Psych v4 breaks our CI running on Ruby 2.5
Therefore, restrain installation to rdoc-6.3.x until we stop testing with Ruby 2.5.
=> Lock `rdoc` gem to v6.3.x to avoid Psych 4.0

.github/workflows/ci.yml, jekyll-import.gemspec, test/helper.rb, test/test_blogger_importer.rb, test/test_csv.rb, test/test_jrnl_importer.rb, test/test_mt_importer.rb, test/test_roller_importer.rb, test/test_tumblr_importer.rb, test/test_wordpress_importer.rb, test/test_wordpressdotcom_importer.rb
=> Bump dependencies and CI Ruby versions

.github/workflows/docs.yml
Similar to how the docs are deployed for the Jekyll Core repository.
- **Allow building with plugins to inject data at runtime.**
- Allow building with latest version of Jekyll.
=> Build and deploy docs site via GitHub Actions

jekyll-import.gemspec, script/build-docs
Avoid installing importer dependencies and test-suite dependencies while building / deploying the documentation site.
While setting-up *Deploy Previews* (on `pull_request` events) for the docs-site via Netlify. the build-image there failed to install certain gems with native=extensions due to missing dependencies of the native-code compiler.
- Lesser number of gems to install.
- Using conditional block in the gemspec instead of a Bundler group in the Gemfile means dev-dependencies continue getting listed at the Rubygems.org page as is current behavior.
=> Omit importer dependencies in docs-site workflow

Rakefile, docs/_docs/history.md
Basically, update Rakefile to emulate Jekyll Core repository in how the pre-generated `docs/_docs/history.md` handles escaped sequences of the form `&#NUM;`.
=> Fix generation of History doc for docs-site

lib/jekyll/commands/import.rb
After:
```console
jekyll import
You must specify an importer. 
Valid options are: 
* behance
* blogger
* csv
* dotclear
* drupal6
* drupal7
* drupal8
* easyblog
* enki
* ghost
* googlereader
* joomla
* joomla3
* jrnl
* marley
* medium
* mephisto
* mt
* pluxml
* posterous
* roller
* rss
* s9y
* s9ydatabase
* textpattern
* tumblr
* typo
* wordpress
* wordpressdotcom
```
=> import command: sort list of importers when printing

lib/jekyll-import/importers/blogger.rb
This was how URI.decode was implemented.
Removed in https://github.com/ruby/uri/commit/61c6a47ebf
Fixes #509.
=> Replace URI.decode with URI::DEFAULT_PARSER.unescape

lib/jekyll-import/importers/dotclear.rb
This change is purely for cosmetic reasons and have no functional changes.
The motivation behind this is to produce a saner diff in #512 which re-implements the importer, changing the Ruby API of the importer.
=> Refactor Dotclear importer methods into singleton instance methods

History.markdown, docs/_docs/history.md, lib/jekyll-import/version.rb
Fixes https://github.com/jekyll/jekyll-import/issues/498.
=> Release v0.22.0

lib/jekyll-import/importers/wordpressdotcom.rb
While importing one of the Turkish websites, I noticed ruby HTTP library was not able to download because of the non-ASCII characters.
So I used escape while download process.
An example command
```bash
ruby -r rubygems -e 'require "jekyll-import";JekyllImport::Importers::WordpressDotCom.run({"source" => "wordpress.xml","no_fetch_images" => false, "assets_folder" => "assets" })'
```
=> Escape non ascii-characters while image downlading from wordpress

README.markdown, docs/_docs/contributing.md, docs/_layouts/importer.html, exe/jekyll-import, jekyll-import.gemspec
We have been asking folks to run `jekyll import` for a while, but it requires a `Gemfile`. Not everyone wants to have a Gemfile or knows how to set one up. I'd like to be a bit more independent of Jekyll and its not-always-entirely-working system for external subcommands.
This commit adds a new top-level 'jekyll-import' command so that this gem can handle importing without requiring a Gemfile with `:jekyll_plugins`.
The flow is still rather tedious:
1. Run `jekyll-import` to see subcommands
2. Run `jekyll-import <subcommand> --help` to see options
3. Run `jekyll-import <subcommand> <options>` but get a dependency-not-found error
4. Run `gem install <dependency1>` to install
5. Re-run `jekyll-import <subcommand> <options>` but get another dependency-not-found error.
6. Run `gem install …
=> Add jekyll-import command

exe/jekyll-import
=> Require jekyll-import/version so JekyllImport::VERSION can be read.

docs/_config.yml
Hi,
while browsing https://import.jekyllrb.com/docs/wordpress/ I realized [View Source](https://github.com/jekyll/jekyll-import/blob/v0.14.0/lib/jekyll-import/importers/wordpress.rb) on that page is a little out of date.
Here's a possible fix.
Another option would be to point to latest tip of tree, e.g. https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/wordpress.rb
by changing https://github.com/jekyll/jekyll-import/blob/d332fa22c68c9e0fc1149f0579f017c659130e37/docs/_layouts/docs.html#L42
Have a nice week
midzer
=> docs: update latest release to 0.24.0

exe/jekyll-import, lib/jekyll-import/importers/pebble.rb
Follow up to https://github.com/jekyll/jekyll-import/pull/544
=> fix RuboCop

lib/jekyll-import/importers/pebble.rb
(Trying) to fix https://github.com/jekyll/jekyll-import/pull/545
=> Fix erroneous cosmetic changes in Pebble importer
