jekyll/jekyll-import

site/_docs/usage.md

Not sure if this should be on the master branch or gh-pages, so there’s a second pull request coming.

Update Usage documentation to match code example

---

README.markdown

instruction for usage with jekyll v3

---

lib/jekyll-import/importers/drupal6.rb

Exactly the same thing as #230 but for Drupal 6 :)
This adds a --types command line option to allow the user to specify which node types to import from Drupal 6. This way the user can also import pages or any other content type.
It defaults to the ones the importer already did (blog posts, articles and stories), so that users are not forced to specify the node types and thus they won't see a difference if they don't need this ability.

Allow importing any Drupal 6 node type

---

site/_importers/drupal6.md

Saving you some work: this time I didn't forget to include the documentation changes :)

Add documentation for Drupal 6 'types' param. Ref #231

---

lib/jekyll-import/importers/mt.rb

Fixes #223
To use this patch, put the following in your `Gemfile`:
```ruby
gem "jekyll-import", github: "jekyll/jekyll-import", branch: "mt-use-sequel"
```
Then run `bundle install` and `bundle exec irb -rjekyll-import`. Then run the command per the docs specifying the `dbname` option as the path to your SQLite database file.

MT: allow use of SQLite for installation.

---

Gemfile
lib/jekyll-import/importers/csv.rb
test/test_csv.rb

CSV: parse the post using a class which errors on missing data.

---

site/index.html

Hi @parkr, :smiley:
I correct the ***"How to Contribute"* link** in `site/index.html`. :pencil:
*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

Correct "How to Contribute" link

---

History.markdown
site/_docs/contributing.md

@pathawks @parkr 
New pull request of #245!

Correct "our community forum" link

---

lib/jekyll-import/importers/tumblr.rb

Tumblr: look up beginning and end of JSON dynamically

---

.rubocop.yml
jekyll-import.gemspec
script/cibuild
script/fmt

Inherited the jekyll/jekyll rubocop config.
Runs in CI but doesn't fail the build yet.

Add rubocop

---

lib/jekyll-import/importers/tumblr.rb

Fixes this: https://github.com/jekyll/jekyll-import/issues/256#issuecomment-231202004

tumblr: only append to content if its truthy

---

lib/jekyll-import/importers/tumblr.rb

Tumblr: fix creation of rewrite rules

---

_includes/top.html

The site is currently not loading the styles, because of the protocol discrepancy.
This should fix it 😉

Fixed style issues on HTTPS site

---

docs/_importers/wordpress.md

Missed this before when reviewing and merging #311

Add the new port setting to the Wordpress importer docs

---

lib/jekyll-import/importers/wordpressdotcom.rb

I found this really useful personally, please feel free to turn down if it's not needed.

Add parent_id to wordpressdotcom importer

---

docs/_importers/drupal7.md
lib/jekyll-import/importers/drupal6.rb
lib/jekyll-import/importers/drupal7.rb
lib/jekyll-import/importers/drupal_common.rb

* Support Drupal 7 installations with PostgreSQL database.
* Updated documentation with an example.
* Minor bug fixes.

Add support for Drupal 7 installations with PostgreSQL database

---

lib/jekyll-import/importers/behance.rb
lib/jekyll-import/importers/blogger.rb
lib/jekyll-import/importers/csv.rb
lib/jekyll-import/importers/drupal_common.rb
lib/jekyll-import/importers/easyblog.rb
lib/jekyll-import/importers/enki.rb
lib/jekyll-import/importers/joomla.rb
lib/jekyll-import/importers/joomla3.rb
lib/jekyll-import/importers/jrnl.rb
lib/jekyll-import/importers/mephisto.rb
lib/jekyll-import/importers/mt.rb
lib/jekyll-import/importers/posterous.rb
lib/jekyll-import/importers/s9y_database.rb
lib/jekyll-import/importers/textpattern.rb
lib/jekyll-import/importers/tumblr.rb
lib/jekyll-import/importers/typo.rb
lib/jekyll-import/importers/wordpress.rb
lib/jekyll-import/importers/wordpressdotcom.rb

Align importer options' parameters for readability

---

docs/_docs/contributing.md

Update the document to enable easier contribution from the community.

Update Documentation for Contributing to project

---

.rubocop.yml
lib/jekyll-import/importers/tumblr.rb

- Simplify conditionals with guard clauses
- Improve readability with whitespace
- Follow DRY principle
- Parallel assignments and String interpolations
- Freeze string literals to reduce allocations

Refactor Tumblr Importer

---

lib/jekyll-import/importers/tumblr.rb

Patch missing per_page bug in Tumblr importer

---

test/test_tumblr_importer.rb

To avoid extended horizontal scrolling while manually reading the payload..

Prettify JSON payloads in test_tumblr_importer

---

docs/_importers/wordpressdotcom.md

Add note to install required additional gems.

Add install additional gems note

---

jekyll-import.gemspec
lib/jekyll-import/importers/mephisto.rb

Remove deprecated use of fastercsv

---

lib/jekyll-import/importers/blogger.rb

- A helper that acts as an *accessor* for `@in_entry_elem[:meta]`
- A helper to compute *`in_entry_element_modified_time`*

Add private helpers to simplify Blogger importer

---

lib/jekyll-import/importers/drupal6.rb

Hi there,
i think, it would be great to retain the Drupal url_alias as permalink in imported nodes.
so i...
- extended the query to be able to fetch url_alias.src
-  assigned permalink within Front Matter
Regards
Florian

drupal6: retain url_alias.dst as permalink in imported nodes

---

docs/_importers/wordpressdotcom.md

wordpressdotcom: add install additional gem note in docs

---

docs/_importers/drupal8.md
docs/_importers/easyblog.md

I accepted https://github.com/jekyll/jekyll-import/pull/405 before there were docs, oops!
Pre-requisite of https://github.com/jekyll/jekyll-import/pull/442.

Add Drupal 8 docs

---

.github/workflows/release.yml

Trigger a release when changes to `lib/**/version.rb` is pushed to `master`.

Add workflow to automate tagging and releasing gem

---

lib/jekyll-import/importers/pebble.rb

[Pebble](https://pebble.sourceforge.net) is a blog based with XML source files. Sadly it is EOL.
This script will enable folks to import their blog in to Jekyll, leveraging Nokogiri.

add pebble importer

---

docs/_importers/csv.md
docs/_importers/drupal6.md
docs/_importers/googlereader.md
docs/_importers/marley.md
docs/_importers/mephisto.md
docs/_importers/mt.md
docs/_importers/pebble.md
docs/_importers/pluxml.md
docs/_importers/posterous.md
docs/_importers/roller.md
docs/_importers/rss.md
docs/_importers/textpattern.md
docs/_importers/wordpress.md

Pebble importer was added in #527.

Update docs: fix order of importers & add pebble importer
